apiVersion: v1
kind: ServiceAccount
metadata:
  name: retag-image-sa
  namespace: default
  labels:
    app.kubernetes.io/name: retag-image
    name: retag-image
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: retag-image-cluster-role
  labels:
    app.kubernetes.io/name: retag-image
    name: retag-image
rules:
- apiGroups: ["apps"]
  resources: ["deployments","daemonsets"]
  verbs: ["get","list","watch","patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: retag-image-cluster-role-binding
  labels:
    app.kubernetes.io/name: retag-image
    name: retag-image
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: retag-image-cluster-role
subjects:
- kind: ServiceAccount
  name: retag-image-sa
  namespace: default